const App = {
    data() {
        return {
            appName: "SoftPOS",
            datas: [
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 2.0.6(48)',
                    checkValue: '2025/10',
                    ticketNumber: '',
                    changeLog: 'API35<br>',
                    download: 'https://drive.google.com/file/d/1Gx1lcOEAE84v0HYzdqwabbkhu35xm-IB/view?usp=sharing',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.1.0(47)',
                    checkValue: '2024/06/03',
                    ticketNumber: '',
                    changeLog: '實驗室驗證<br>',
                    download: 'https://drive.google.com/file/d/1V_JfNXzG0kTrXT_zb82a1fJb2kvOE0Hk/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.8',
                    checkValue: '2024/03/15',
                    ticketNumber: '',
                    changeLog: '',
                    download: 'https://drive.google.com/file/d/1NchiWZSTeqCTRlxl5yQ7AKrIbcjRUOd2/view?usp=sharing',
                },
                {
                    supSystem: 'Android',
                    env: 'SIT',
                    appVersion: 'version 2.0.7(57)',
                    checkValue: '2025/12/10',
                    ticketNumber: 'M2025117_R114202',
                    changeLog: 'GMS<br>更新四層憑證<br>',
                    download: 'https://drive.google.com/file/d/164kGCste6cOgvsSn7F9YBN2uMmE-BImt/view?usp=sharing',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.5(40)',
                    checkValue: '2023/12/22',
                    ticketNumber: '',
                    changeLog: '新增生物辨識功能<br>調整登入密碼長度限制<br>調整簽單簽名的品質<br>修正未完成交易時，退貨不得修改金額<br>登入頁新增按鈕-生物辨識登入<br>設定密碼需至少一位大小寫英文及數字<br>',
                    download: 'https://drive.google.com/file/d/1tKUW2U8t4CNWiehlURT-Y3PbsGr9aq0q/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.4(38)',
                    checkValue: '2023/10/11',
                    ticketNumber: '',
                    changeLog: 'New SDK<br>',
                    download: 'https://drive.google.com/file/d/13JsvjhJ_i1xHTUqTOMxAheKJEjxAuUiu/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.4',
                    checkValue: '2023/08/29(38)',
                    ticketNumber: 'M2023066-R112112 M2023106-R112187',
                    changeLog: 'API 33<br>修正crossApp timeout bug<br>修正crossApp init GPS<br>',
                    download: 'https://drive.google.com/file/d/1yt5i_u9z3oYr23KFKGtwxNi19Dr-e2rL/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.3',
                    checkValue: '20230724',
                    ticketNumber: '',
                    changeLog: 'MineSec F項檢測 (混淆) _20230724<br>',
                    download: 'https://drive.google.com/file/d/10pB6VXYHGDzEo_IoMtKEHpr46IA1l2D-/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.3',
                    checkValue: '20230724',
                    ticketNumber: '',
                    changeLog: 'MineSec F項檢測(無混淆) _20230724<br>',
                    download: 'https://drive.google.com/file/d/1gZdiF_c8MF5tbHihwT2LZcejC23_bdTP/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.0(33)',
                    checkValue: '2022/12/09',
                    ticketNumber: '',
                    changeLog: '20221209修正<br>',
                    download: 'https://drive.google.com/file/d/1OEYprfD2hguSowrfVamA4o_WN1Jy2Xvv/view?usp=share_link',
                },
                {
                    supSystem: 'Android',
                    env: 'SIT',
                    appVersion: 'version 1.0.3(36)',
                    checkValue: '2023/05/11',
                    ticketNumber: '',
                    changeLog: 'use NCCC_Dev_210036C_NCCC _SIT_3.license<br>target API 33<br>',
                    download: 'https://drive.google.com/file/d/1_JILH0Zookgd7PosJagzm5dgDEIdD3Ua/view?usp=share_link',
                },
                {
                    supSystem: 'Android',
                    env: 'SIT',
                    appVersion: 'version 1.0.0(31)',
                    checkValue: '2022/11/24',
                    ticketNumber: '',
                    changeLog: '使用新SIT license<br>開EMV_debug<br>',
                    download: 'https://drive.google.com/file/d/1lzq4li-BFlYyo3umVepH2bSrvP-OcYLZ/view?usp=share_link',
                },
                {
                    supSystem: 'Android',
                    env: 'UAT',
                    appVersion: 'version 1.0.0(30)',
                    checkValue: '2022/10/26-01',
                    ticketNumber: '',
                    changeLog: 'PROD<br>',
                    download: 'https://drive.google.com/file/d/1Nu6RPY63uuBV3jaR7T4xFjGXdeqr8Lu0/view?usp=sharing',
                },
                {
                    supSystem: 'Android',
                    env: 'SIT',
                    appVersion: 'version 1.0.4(39)',
                    checkValue: '2023/10/03',
                    ticketNumber: 'M2023135-R112234',
                    changeLog: 'use NCCC_Dev_210036C_NCCC _SIT_3.license<br>Target API 33<br>implement biometric feature<br>modify the limit of password length<br>',
                    download: 'https://drive.google.com/file/d/1W9lb9cX4KYM09kXLeP0N3JM3pqvXXasM/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'SIT',
                    appVersion: 'version 1.0.3(38)',
                    checkValue: '2023/10/03',
                    ticketNumber: 'M2023066-R112112 M2023106-R112187',
                    changeLog: 'API 33<br>修正crossApp timeout bug<br>修正crossApp init GPS<br>',
                    download: 'https://drive.google.com/file/d/1Bbr9Up1a1maooOHb2cUqc4kAdrIQSbjW/view?usp=drive_link',
                },
                {
                    supSystem: 'Android',
                    env: 'SIT',
                    appVersion: 'version 1.0.4(41)',
                    checkValue: '2022/10/17',
                    ticketNumber: 'M2023135-R112234',
                    changeLog: 'use NCCC_Dev_210036C_NCCC _SIT_3.license<br>Target API 33<br>implement biometric feature<br>modify the limit of password length<br>use MineHades-2.10.40C-f3e0a4ca<br>',
                    download: 'https://drive.google.com/file/d/1y5dn3Cb4Bt6keCflbTUm263FJx3FPIdh/view?usp=drive_link',
                },
            ]
        }
    }
}
